#!/bin/bash
#
# Example script found at https://github.com/fhd/init-script-template
#
# chkconfig: 345 99 01
#
dir="/var/app"
cmd="dotnet /var/app/DataDogLogging.dll --urls=http://*:80"
user=""

name=`basename $0`
pid_file="/var/run/$name.pid"
stdout_log="/var/log/app.log"
stderr_log="/var/log/app.err"

get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && (( $(ps -ef | grep -v grep | grep "$pid_file" | wc -l) > 0 ))
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Configuring app"

        
        echo "Starting app"
        cd "$dir"
        if [ -z "$user" ]; then
            sudo $cmd >> "$stdout_log" 2>> "$stderr_log" &
        else
            sudo -u "$user" $cmd >> "$stdout_log" 2>> "$stderr_log" &
        fi
        echo $! > "$pid_file"

        if ! is_running; then
            echo "Unable to start, see /var/log/messages or cloudwatch org/EC2/messages"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill `get_pid`
        for i in 1 2 3 4 5 6 7 8 9 10
        # for i in `seq 10`
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0